# Rules for Kanvas-site
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "content/**/*"
          - "**/*.md"
area/ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"
area/ui:
  - changed-files:
      - any-glob-to-any-file:
          - "assets/**/*"
          - "static/**/*"
          - "layouts/**/*"
          - "i18n/**/*"
          - "hugo.toml"
area/maintainers:
  - changed-files:
      - any-glob-to-any-file:
          - "Makefile"
          - "package.json"
          