#!/usr/bin/env bash
# Prevents editing files inside public/ (Hugo build output).
# public/ is fully regenerated by `make build` — edits there are silently wiped.
#
# Usage as an AI coding assistant hook (PreToolUse):
#   Tool input arrives as JSON on stdin; exits 2 to block with a message.
#
# Usage as a git pre-commit hook:
#   ln -s ../../scripts/hooks/block-public-edits.sh .git/hooks/pre-commit
#   When invoked by git, stdin is a terminal — staged paths are inspected and
#   the commit is blocked if any files under public/ are included.

set -euo pipefail

# If stdin is a terminal, assume git pre-commit hook context and inspect staged files.
if [ -t 0 ]; then
  if git rev-parse --git-dir >/dev/null 2>&1; then
    while IFS= read -r path; do
      if [[ "$path" == public/* ]] || [[ "$path" == */public/* ]]; then
        echo "ERROR: Cannot commit files in public/ — it is Hugo build output." >&2
        echo "Edit source files in layouts/, assets/, static/, or content/ instead." >&2
        echo "Run 'make build' to regenerate public/ from sources." >&2
        exit 1
      fi
    done < <(git diff --cached --name-only)
  fi
  exit 0
fi

file_path=$(python3 -c "
import sys, json
try:
    print(json.load(sys.stdin).get('file_path', ''))
except Exception:
    print('')
" 2>/dev/null || echo "")

if [[ "$file_path" == public/* ]] || [[ "$file_path" == */public/* ]]; then
  echo "ERROR: Cannot edit files in public/ — it is Hugo build output." >&2
  echo "Edit source files in layouts/, assets/, static/, or content/ instead." >&2
  echo "Run 'make build' to regenerate public/ from sources." >&2
  exit 2
fi
